### ISSUE TITLE
Automate CheatEngine build (ceserver, android)

### ISSUE THREAD

**Issue by mon231** [cheat-engine/cheat-engine#2687]
One of the main reasons people not using CheatEngine for android is that they do not have any simple installable app / executable. Compiling the project takes a lot of time and energy, requires the user to install many softwares and spend a whole afternoon..
Automating build (at least for ceserver, linux/android) would be as simple as:
```
steps:
  - uses: actions/checkout@v3
  - uses: nttld/setup-ndk@v1
    with:
      ndk-version: r25c
  - runs: ndk-build NDK_PROJECT_PATH="Cheat Engine/ceserver/ndk-build/EXECUTABLE" APP_BUILD_SCRIPT="Cheat Engine/ceserver/ndk-build/EXECUTABLE/Android.mk" NDK_APPLICATION_MK="Cheat Engine/ceserver/ndk-build/EXECUTABLE/Application.mk"
```

It will make it much easier to download&install, forcing merged code to be compilable, and potentially auto-include build artifacts in tagged releases!
